spring:
  application:
    name: eureka-client-2
server:  port: 8002
eureka:  client:    service-url:      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
     prefer-ip-address: true