spring:
  application:
    name: eureka-zuul
server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: '${EUREKA_URI:http://localhost:8761/eureka}'
  instance:
    prefer-ip-address: true
zuul:
  routes:
    client1:
      path: /client1/**
      service-id: eureka-client-1
    client2:
      path: /client2/**
      service-id: eureka-client-2